### ISSUE TITLE
Document annotation processing

### ISSUE THREAD

**Issue by WonderCsabo** [groovy/groovy-android-gradle-plugin#105]
I managed to make ["annotation processing"](https://docs.gradle.org/2.4-rc-1/release-notes#support-for-“annotation-processing”-of-groovy-code) work on a [Groovy Android Gradle project](https://github.com/WonderCsabo/androidannotations/blob/groovyExample/examples/groovy/build.gradle).

I updated the Android Gradle Plugin from 1.2.3 to 1.5.0 and the Groovy Android Gradle plugin from 0.3.6 to 0.3.9, and annotation processing no longer works. The processor is initialised, but no processing rounds are started.

Issue originally opened against the [android-apt](https://bitbucket.org/hvisser/android-apt/issues/63/groovy-processing-no-longer-works) plugin.

**Comment by pieces029** [comment]
Could you provide a sample, or even better write a functional test that is not working? I am currently working on an example project and it has been working fine.

**Comment by WonderCsabo** [comment]
I linked my [example project](https://github.com/WonderCsabo/androidannotations/blob/groovyExample/examples/groovy/build.gradle) in the OP. :wink:

**Comment by pieces029** [comment]
You don't have gradle set to run the annotation processor.

```groovy
androidGroovy {
  options {
    configure(groovyOptions) {
      javaAnnotationProcessing = true
    }
  }
}
```

**Comment by WonderCsabo** [comment]
@pieces029 This does not help, and actually this is not necessary, because the `android-apt` plugin already [sets that property](https://bitbucket.org/hvisser/android-apt/src/a72b4ae9be9667b7cac056c1f89b04f847ea7edd/src/main/groovy/com/neenbedankt/gradle/androidapt/AndroidAptPlugin.groovy?at=default&fileviewer=file-view-default#AndroidAptPlugin.groovy-105).

But i added that snippet and it is still not working. I reverted to Groovy Android Gradle Plugin 0.3.6 and Android Gradle Plugin 1.2.3, and the same project immediately worked, so i am pretty sure something went wrong in the newer plugin versions.

**Comment by pieces029** [comment]
Here is what I'm doing for databinding, which uses annotation processing.
https://github.com/pieces029/groovy-android-data-binding/blob/master/build.gradle
The Apt Plugin didn't work until I set `javaAnnotationProcessing = true`
I don't think the skipJavaC is required, I just wanted groovy to compile everything.

I am currently working on a dagger sample, which does not use this plugin and everything is also working fine, as long as I have `javaAnnotationProcessing = true`.

This sounds more like a problem with the apt plugin if anything, although javaCompile is still finalized by groovy compile so that should all be working correctly too.

**Comment by pieces029** [comment]
Oh, you need to have the groovy plugin before the apt plugin :)

**Comment by pieces029** [comment]
Opening as a ticket for adding documentation around annotation processing.

**Comment by WonderCsabo** [comment]
@pieces029 thanks, changing the plugin order indeed works!

**Comment by hvisser** [comment]
Not sure why order matters, since `android-apt` uses `project.afterEvaluate()`. I guess Gradle will still order  that call in some way.

**Comment by pieces029** [comment]
Added in #115
