### ISSUE TITLE
Update to Work with Jack and Jill Compiler

### ISSUE THREAD

**Issue by AndrewReitz** [groovy/groovy-android-gradle-plugin#113]
In 2.0.0 jack and jill compilation was released. To stay ahead of the changes try it out and update the plugin accordingly.

**Comment by pieces029** [comment]
After more research, javac + groovyc + dex is actually faster. Also Jack and Jill have many other issues with other tools plugins and libraries such at at this time it is best to leave the plugin the way it is.

**Comment by pablisco** [comment]
Is there something special needed to make it work?

**Comment by pieces029** [comment]
Yes, groovy code would need to be compiled to .class files and then compiled again by Jill.

**Comment by pieces029** [comment]
Jack & Jill are starting to look more promising. Reopening issue to investigate.

**Comment by AndrewReitz** [comment]
Looks like this isn't a feature we need to worry about. 

https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html
