### ISSUE TITLE
Error:Class com.android.build.gradle.internal.scope.VariantScopeImpl does not implement the requested interface com.android.build.gradle.internal.scope.BaseScope

### ISSUE THREAD

**Issue by henriquedesousa** [groovy/groovy-android-gradle-plugin#117]
If the android gradle plugin is updated to 2.2.0-alpha5 (using Android Studio 2.2.0-alpha5), we start getting the following error while syncing gradle files:

`Error:Class com.android.build.gradle.internal.scope.VariantScopeImpl does not implement the requested interface com.android.build.gradle.internal.scope.BaseScope`

If we comment out the plugin, it will work.

`classpath 'org.codehaus.groovy:groovy-android-gradle-plugin:1.0.0' 
apply plugin: 'groovyx.android'`

I've gisted a logfile with the corresponding error messages: https://gist.github.com/henriquedesousa/61fe25cb273637eacaaef2fa27532abb

I also tried the 1.0.1-SNAPSHOT, but the outcome is the same. Thank you for your help.

**Comment by Naitbit** [comment]
I've added compatibility in https://github.com/groovy/groovy-android-gradle-plugin/pull/118
since mostly all that was needed was bumping plugin dependencies (and one other small change)

**Comment by henriquedesousa** [comment]
Many thanks @Naitbit
