### ISSUE TITLE
Unable to load class 'com.android.build.gradle.internal.scope.BaseScope'

### ISSUE THREAD

**Issue by fattchris** [groovy/groovy-android-gradle-plugin#121]
While attempting to upgrade to Gradle 2.2.0 Alpha 6, I get this issue and applying the plugin fails. This works fine with Gradle 2.1.2.

**Comment by fattchris** [comment]
It looks like there is a PR for this already even..........

**Comment by pieces029** [comment]
Alpha and beta versions of the android plugin are not supported. When 2.2.0 is officially released that PR will be merged in.

**Comment by AHarazim** [comment]
@pieces029 Hi, can you merge the PR since android plugin 2.2.0 stable is released now?

**Comment by pieces029** [comment]
@AHarazim this has been merged. As well as the update to 2.2.0. It has not yet been released as I'm working on a few documentation changes so it is available in the snapshot.

If you do not want to use the snapshot version you can simply exclude the version that 
the plugin was built with and include whatever version you want.
```
classpath('org.codehaus.groovy:groovy-android-gradle-plugin:1.0.0') {
  exclude group: 'com.android.tools.build'
}
```

**Comment by AHarazim** [comment]
@pieces029 Ok, thx for you quick response! ;-)

**Comment by byencho** [comment]
@AHarazim Did the "exclude group: 'com.android.tools.build'" solution work for you? I'm still getting the same error whether I include that or not.

**Comment by pieces029** [comment]
Anyone want to give the snapshot a once over? I'm prepping to release today.
