### ISSUE TITLE
Is 1.1.0 actually available yet?

### ISSUE THREAD

**Issue by byencho** [groovy/groovy-android-gradle-plugin#126]
The README instructions have not been updated and I can't seem to pull it down from jcenter.

**Comment by pieces029** [comment]
No, https://github.com/groovy/groovy-android-gradle-plugin/releases

See on how to use 2.2.0 with 1.0.0 of this plugin https://github.com/groovy/groovy-android-gradle-plugin/issues/121#issuecomment-248320583

**Comment by byencho** [comment]
Cool, thanks @pieces029 .
