### ISSUE TITLE
It breaks the bootClassPath for compileJava

### ISSUE THREAD

**Issue by bladeworks** [groovy/groovy-android-gradle-plugin#133]
I am using jdk 8 and the source code compatibility version set to 1.7. Apply the plugin (1.1.0) to a android library project and then run compileReleaseJavaWithJavac or compileDebugJavaWithJavac, it will get a warning: bootstrap class path not set in conjunction with -source 1.7. However, if I didn't apply the groovy plugin, everything is fine. This only happens when using the plugin in a android library project but not in a android application project.

**Comment by pieces029** [comment]
Does it still compile? A warning is different than breaking. Also, why are you running the compilation tasks directly? Generally running assemble is fine. If you could update the tests to cause this issue that would be a great step for being able to address this issue. https://github.com/groovy/groovy-android-gradle-plugin/blob/master/groovy-android-gradle-plugin/src/test/groovy/groovyx/functional/FullCompilationSpec.groovy#L391

**Comment by bladeworks** [comment]
I can't reproduce it with the test. My project is much complex than the test project.

Actually, it fails when using the proguard to process the class files.  It seems something conflict with the plugin as it works well if I didn't apply the plugin.

Anyway, I will try to update the issue if get any update. For now, please close it as I can't get more helpful information. Thanks.
