### ISSUE TITLE
is it support groovy MOP?

### ISSUE THREAD

**Issue by lchli** [groovy/groovy-android-gradle-plugin#136]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use [Stack
       Overflow](https://stackoverflow.com/questions/tagged/groovy-android) with the android-groovy tag.

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. See [here](https://github.com/groovy/groovy-android-gradle-plugin/tree/master/gradle-groovy-android-plugin/src/test/groovy/groovyx)
       for some example tests.

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by pieces029** [comment]
Hi @lchli this is a place to present issues for the project and not ask questions. 

I'm not sure what MOP is but this plugin is only for running groovy files through the groovy compiler and then providing them to the dexer to make them compatible for Android and supports all language features the version of groovy you are using provides.

**Comment by sergiodelamoshoptimix** [comment]
> A Meta-Object Protocol (MOP) refers to the capabilities in a dynamic language that enable metaprogramming. In Groovy, the MOP consists of four distinct capabilities within the language: reflection, metaclasses, categories, and expandos.

As far as I understand using Groovy for Android Development should focus in using groovy as a statically compiled language thanks to the @CompileStatic annotation. I've however used categories (e.g. [TimeCategory](http://docs.groovy-lang.org/latest/html/api/groovy/time/TimeCategory.html)) in android apps. @lchli  Just bear in mind to use as much statical compilation as possible due to performance reasons.

**Comment by lchli** [comment]
Ok,i should use statical compilation in android.Thanks @sergiodelamoshoptimix
