### ISSUE TITLE
Reflection Error on older versions of Android

### ISSUE THREAD

**Issue by jmartinesp** [groovy/groovy-android-gradle-plugin#14]
Hello, I tried your plugin on the latests versions of Android and it works great, but I tried it on Genymotion with both 2.3.7 and 4.1.1 targets and got this reflection error on `super.onCreate(savedInstanceState);`:

https://ghostbin.com/paste/9w9he

I tried again with 4.2 and 4.4.2 and it worked as it should, even on an Android L Preview device.

I don't know if there are some limitations that I didn't read or if you were aware of this bug before.

**Comment by ericbourque29** [comment]
Hello! 

2 Years have passed and I get the exact same error when building for android:

warning: Ignoring InnerClasses attribute for an anonymous inner class
(groovyjarjarantlr.TokenStreamRewriteEngine$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(groovyjarjarantlr.build.ANTLR$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
warning: Ignoring InnerClasses attribute for an anonymous inner class
(groovyjarjarantlr.debug.misc.ASTFrame$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Does anyone have a fix for this please?

**Comment by blackdrag** [comment]
groovyjarjarantlr.debug.misc.ASTFrame$1 is not a class produced by groovy. It comes from antlr and jarjar has been used to change the package for a bigjar version, which includes antlr already. There should be no reflective operations on that class. So this should be no problem normally. That´s why they are warnings, not errors. How does this prevent you from working with the plugin?
