### ISSUE TITLE
Update to support `annotationProcessor` configuration

### ISSUE THREAD

**Issue by ivangonzalez88** [groovy/groovy-android-gradle-plugin#142]
Hi, 

I am using the  groovy plugin in order to use Spock framework. Recently we added a library for runtime permissions in android 
[https://github.com/hotchemi/PermissionsDispatcher ](url)  which uses annotation processors, the library is generating the class files, i am able to see them, but when the task `compileDebugGroovyWithGroovyc ` runs, it always fails with the below message `/Users/ionzalez/Documents/twc/flagship_phone/app/src/main/java/com/weather/commons/ups/ui/AbstractLoginActivity.java:206: error: cannot find symbol
            AbstractLoginActivityPermissionsDispatcher.loginWithGooglePlusWithCheck(AbstractLoginActivity.this);
            ^
  symbol:   variable AbstractLoginActivityPermissionsDispatcher
  location: class AbstractLoginActivity.GoogleLoginWithGooglePlusWithCheck`
This happen for all the generated classes by the processor, but somehow groovy compiler does not pick them. If i remove the plugin everything works fine `apply plugin: 'groovyx.android'
`
We were able to run spock test before, and it worked well with the permissions library. I started noticing this problem after removing `android-apt` plugin, which is deprecated.

this is my configuration
        `classpath 'org.codehaus.groovy:groovy-android-gradle-plugin:1.1.0'`
        `apply plugin: 'groovyx.android'`
       //groovy and spock dependency
       ` testCompile 'org.codehaus.groovy:groovy-all:2.4.7:grooid'`
       ` testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'`
       //Permissions dependency
`annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.3.2`
`compile 'com.github.hotchemi:permissionsdispatcher:2.3.0'` 
       
Thanks & Regards

**Comment by AndrewReitz** [comment]
Have you followed the steps in the [README.md](https://github.com/groovy/groovy-android-gradle-plugin#annotation-processing) about annotation processing with the plugin?

**Comment by ivangonzalez88** [comment]
Yes i try it.

`androidGroovy {
  options {
    configure(groovyOptions) {
      javaAnnotationProcessing = true
    }
  }
}`
The android-apt plugin is deprecated [http://www.littlerobots.nl/blog/Whats-next-for-android-apt/](url), as soon as i got rid of it, it started failing.

**Comment by AndrewReitz** [comment]
Have you tried skipping javac and only haveing groovyc run as well? 

If you could please provide a failing test for this it would be helpful for debugging.

**Comment by AndrewReitz** [comment]
@ivangonzalez88 any update on this?

**Comment by ivangonzalez88** [comment]
Hi, i could not work around on this, not skipping java c or using joint compilation worked. We disable it for now since we are using 2.4-dev version from gradle, maybe this 2.4-dev version of the gradle plugin is somehow affecting.

**Comment by rdietrichberlin** [comment]
Running into the same issue within android plugin 2.3.1 which includes annotation processing [1] :
dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath 'org.codehaus.groovy:groovy-android-gradle-plugin:1.1.0'
}
As mentioned in the README.md:

"Important android-apt must be applied after the groovy android plugin."

This could not be satisfied, because of the annotation processing is included in com.android.tools.build:gradle!

[1] https://bitbucket.org/hvisser/android-apt/wiki/Migration

**Comment by AndrewReitz** [comment]
On my project updating to use the `annotationProcessor` configuration instead of apt does not cause this error, but also appears to not run that annotation processor.

**Comment by sgara** [comment]
Same problem here :( Using `annotationProcessor` does not run. Using groovy for unit test with Spock only. Dagger and Databinding generated classes end up "not existing"
Any update/idea on this?

**Comment by AndrewReitz** [comment]
Fixed in #149 which should be deployed in the snapshot if you want to try it out.

**Comment by AndrewReitz** [comment]
Merged into 1.2.0 branch
