### ISSUE TITLE
AST Transformations not working

### ISSUE THREAD

**Issue by jmartinesp** [groovy/groovy-android-gradle-plugin#15]
After trying to make a custom AST transformation work on Android for a few hours I haven't been able to.

So, I tried creating a new AST Transformation class using Singleton Transformation source code and I found that while it works on IntelliJ it won't work on Android Studio and Gradle, AST processing doesn't run at all.

The weird thing is that the original Singleton does work on AS, while the copy doesn't.

**Comment by Ufkoku** [comment]
@Arasthel, I have the same issue, tried to move annotation and processor to another module but it doesn't help. Can you share how you connected groovy plugin and lib module to app module?
