### ISSUE TITLE
Compatibility with Gradle 6.0

### ISSUE THREAD

**Issue by autonomousapps** [groovy/groovy-android-gradle-plugin#176]
Application of this plugin leads to the emission of some build deprecations (see image below, which comes from a Gradle build scan). Are there plans to migrate to the newer APIs in order to be compatible with Gradle 6.0?

![Screenshot from 2019-09-10 16-15-02](https://user-images.githubusercontent.com/5402301/64657007-627feb00-d3e6-11e9-9aeb-f477e844c407.png)

**Comment by mrmike** [comment]
Any update on this?

**Comment by autonomousapps** [comment]
Fixed in https://github.com/groovy/groovy-android-gradle-plugin/pull/177
