### ISSUE TITLE
Not recognizing tests written in groovy

### ISSUE THREAD

**Issue by zhihan** [groovy/groovy-android-gradle-plugin#33]
The test classes in src/androidTest/java directory will be picked up by default. However, the groovy source files in src/androidTest/groovy directory are not compiled. Reading the source code of the plugin I would expect it to work.

See https://github.com/zhihan/groovyandroid for an example.

**Comment by zhihan** [comment]
I just want to report some of my further investigation. The Groovy files in the "src/androidTest/grovvy" directory was compiled and generated to the right place. However, the task to generate test-classes for JAVA is called compileTestDebugJava instead of compileDebugTestJava (compared to 'compileDebugTestGroovy' in the plugin).

**Comment by pieces029** [comment]
Your test is using robolectric. The androidTest folder is for Android unit tests.

**Comment by zhihan** [comment]
I don't think that is the issue. The Robolectric tests written in JAVA in the same directory works fine. BTW I have also tried to put the unit tests in src/test/groovy directory, adding sourcesets specifying the directory, and replacing Robolectric with the testing framework provided by android sdk with no success. 

BTW, could you also explain what is the difference between "Android unit tests" and Robolectric, a unit testing framework written for Android?

**Comment by pieces029** [comment]
Robolectric is  bunch of stubs written so that you can run unit tests on the JVM. Android unit tests are actually run on the device. I'm guessing that if you want to run robolectric you will need to load groovy-all instead of grooid and use the groovy plugin.

**Comment by zhihan** [comment]
Thanks. I think the issue is that the groovy-android plugin does not work with the Robolectric plugin. It was the Robolectric plugin that performs the tasks of unit testing, not the android plugin from android sdk.     Feel free to close this issue if you want. It is more of a feature request than bug.

**Comment by pieces029** [comment]
It's been a while since I've used Robolectric, but if you want to use groovy with it I would recommend looking into Robospock.

**Comment by jaredsburrows** [comment]
@zhihan Please see this repository using the latest snapshot: https://github.com/morgotth/AndroidJavaAlternatives. There is no reason your tests should not pass.
