### ISSUE TITLE
Incremental builds do not work. 

### ISSUE THREAD

**Issue by Mohitpandey** [groovy/groovy-android-gradle-plugin#34]
Fresh clone of a project and building fails but following builds will pass. The problem is easily reproducible by simply deleting the build directory which our build server does every time.

To make it easier to debug I have added a sample project in git ( https://github.com/Mohitpandey/groovy_build_bug). Reproduction steps are in the README file. This project was build using default template that Android studio uses to make a sample app. All it does is add groovy support using the latest version of the plugin.

**Comment by mg6maciej** [comment]
I "fixed" it on Travis CI by running `./gradlew build` twice as follows:

    install:
      - ./gradlew build || true
      - ./gradlew build

**Comment by pieces029** [comment]
@Mohitpandey I updated the sample project you have to use the 0.3.6 version of this plugin, groovy 2.4.4, and android tools 1.2.0 and `./gradlew clean build` works fine.

Closing this issue, but feel free to open it again if you are seeing this problem after updating the project.
