### ISSUE TITLE
Add tasks to support (new) native unit tests in android

### ISSUE THREAD

**Issue by pjakubczyk** [groovy/groovy-android-gradle-plugin#37]
Recently google release plugin v.1.1.0 which gives possibility to run regular jUnit tests. http://tools.android.com/tech-docs/unit-testing-support

Would it be possible to extend the plugin to compile src/test/groovy and bind it after 'compile{BuildType}UnitTestJava' ?

**Comment by pjakubczyk** [comment]
@melix I've seen that you have updated the plugin to use 1.1.0 Android plugin but you're still reading from androidTest directory

**Comment by melix** [comment]
I didn't have time to check what is wrong actually. I am a bit annoyed that they change the API or layout so often... If you have an idea I would be very happy if you can submit a PR because I am very busy.

**Comment by andresviedma** [comment]
@pjakubczyk it should be working now, with today's changes.

**Comment by pjakubczyk** [comment]
@andresviedma thanks a lot! I will check it out in my project over the weekend

**Comment by pjakubczyk** [comment]
Works like charm! thanks

**Comment by jaredsburrows** [comment]
@pjakubczyk Can this be closed now?

**Comment by pjakubczyk** [comment]
Yes, please.
