### ISSUE TITLE
Plugin not available in mavenCentral() despite README.md stating we could use it instead.

### ISSUE THREAD

**Issue by djmittens** [groovy/groovy-android-gradle-plugin#42]
So i just had mavenCentral() in my buildscript repositories directive however it was not available until i added jcenter()

**Comment by pieces029** [comment]
The README only specifies mavenCentral for the grooid jar.

**Comment by melix** [comment]
Indeed, the plugin is only available in JCenter, but the Groovy jar is available in both. In any case, better use JCenter (faster).
