### ISSUE TITLE
Does not work with com.android.tools.build:gradle:1.1.0+

### ISSUE THREAD

**Issue by jaredsburrows** [groovy/groovy-android-gradle-plugin#44]
The latest `com.android.tools.build:gradle` is `com.android.tools.build:gradle:1.1.3`.

The version that this plugin **does work** is `com.android.tools.build:gradle:1.0.0`.

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:1.1.0' // <--
            classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.5'

            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }

**Error:**

    $ gradlew clean assembleDebug
    Configuration on demand is an incubating feature.
    :clean
    :preBuild UP-TO-DATE
    :preDebugBuild UP-TO-DATE
    :compileDebugNdk UP-TO-DATE
    :checkDebugManifest
    :prepareDebugDependencies
    :compileDebugAidl
    :compileDebugRenderscript
    :generateDebugBuildConfig
    :generateDebugAssets UP-TO-DATE
    :mergeDebugAssets
    :generateDebugResValues UP-TO-DATE
    :generateDebugResources
    :mergeDebugResources
    :processDebugManifest
    :processDebugResources
    :generateDebugSources
    :compileDebugJava
    :compileDebugGroovy FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':compileDebugGroovy'.
    > No such property: bootClasspath for class: com.android.build.gradle.AppPlugin
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    
    BUILD FAILED
    
    Total time: 5.304 secs

I believe a similar fix is here: https://github.com/RoboBinding/RoboBinding-aspectj-plugin/issues/4

**Comment by melix** [comment]
The release 0.3.6 is already out for several weeks now, sorry you didn't notice.

**Comment by stefano-cliqz** [comment]
You should update the README.md, a lot of people just read and copy the instructions

**Comment by jaredsburrows** [comment]
@stefano-cliqz  I have a pull request for it here: https://github.com/groovy/groovy-android-gradle-plugin/pull/45.

**Comment by realgz** [comment]
I addd a line to build.gradle ,It works fine
com.android.build.gradle.AppPlugin.metaClass.getBootClasspath ={ androidBuilder.getBootClasspath true  }

**Comment by jaredsburrows** [comment]
@realgz You should be able to use the latest snapshot.

**Comment by realgz** [comment]
@jaredsburrows  thanks, but 0.3.7-snapshot still has the issue.
