### ISSUE TITLE
Ability to configure groovy sourceSets

### ISSUE THREAD

**Issue by pieces029** [groovy/groovy-android-gradle-plugin#46]
I would like the ability to have the groovy compiler to compile java files. This way I can take an already existing project and add groovy to it.

I think this should be achieved a flag in the options config.

**Comment by safwankamarrudin** [comment]
@pieces029 According to the README file

>Groovy sources must be found inside src/main/groovy. Note that the plugin follows the behavior of the >Groovy plugin in Gradle, which means that if you want to be able to have Groovy classes referencing >Java classes that themselves reference Groovy classes, then those Java classes must be found inside >src/main/groovy too (this is called joint compilation).

Is this what you're after?

**Comment by pieces029** [comment]
Close, but I would like to keep the java files where they are in the `src/$variant/java` folder. With the groovy gradle plugin I could just add that path to the groovy sourceSet.

**Comment by pieces029** [comment]
I also would like to be able to have things in other folders rather than just in a groovy folder. I have been having issues trying to share tests between the JVM and Android test folders. 

On the GroovyCompile task there is an option of [`source`](http://gradle.org/docs/current/dsl/org.gradle.api.tasks.compile.GroovyCompile.html) that can be set using the options in the groovyAndroid configuration, but the JavaCompile task does not skip the java files that were added.

I'm thinking I can fix this with a simple update to the `attachGroovyCompileTask`.

**Comment by pieces029** [comment]
Played around with this a bit more and I think the best option is to have a sourceSet configuration in  androidGroovy.

**Comment by pieces029** [comment]
Added in 0.3.9
