### ISSUE TITLE
Can't evaluate code from Android Studio debugger.

### ISSUE THREAD

**Issue by s0nerik** [groovy/groovy-android-gradle-plugin#47]
When I try to evaluate some code in Android Studio debugger I always get this error:
![](http://i.imgur.com/1t2jlDD.png)

Perhaps it's an issue with Android Studio itself. If it is, please confirm it so I can file this issue to Android Studio's bug tracker.

UPDATE: managed to make it work by changing expression language from Groovy to Java.
![](http://i.imgur.com/zdks9nO.png)

**Comment by pieces029** [comment]
@melix Can this be labeled this as documentation?
