### ISSUE TITLE
Disabling joint compilation

### ISSUE THREAD

**Issue by mg6maciej** [groovy/groovy-android-gradle-plugin#48]
Is the an option in the plugin to disable joint compilation?

After a recent release of Gradle 2.4, we've converted all files to Groovy and I'm wondering if it automatically detects this situation and doesn't create stubs for joint compilation and more importantly if that would make compilation faster.

Thanks,
Maciej

**Comment by pieces029** [comment]
Do you know if the `GroovyCompile` task has joint compilation on by default? The docs don't say anything, but from some of the code I've seen I would believe it is.

@melix @alkemist would either of you know? Is there a parameter that can be passed to options to disable/enable joint compilation?

**Comment by pieces029** [comment]
@mg6maciej Why not just rename the `.java` files that are in the `src/main/groovy` folder to `.groovy` files? As far as compilation speed ups go, I really doubt this will do much. The speed problem is generally in the dexing. You can see what's causing your slowdown with the `--profile` gradle flag.

**Comment by pieces029** [comment]
I haven't heard anything on this in a while, so I will be closing the issue. Please feel free open this again if you feel like I didn't provide enough to go off of.
