### ISSUE TITLE
Document data binding

### ISSUE THREAD

**Issue by psh** [groovy/groovy-android-gradle-plugin#49]
If I write my class
```
@CompileStatic
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState)
        ActivityMainBinding binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
        binding.helloWorld.text = 'Rabbits!'
    }

}
```
I get a compilation error :
```
E:\Devt\LendingLibrary\app\src\main\groovy\com\gatebuzz\lendinglibrary\MainActivity.groovy: 15: [Static type checking] - Cannot assign value of type android.databinding.ViewDataBinding to variable of type com.gatebuzz.lendinglibrary.databinding.ActivityMainBinding
 @ line 15, column 39.
           ActivityMainBinding binding = DataBindingUtil.setContentView(this, R.layout.activity_main)
                                         ^
Error:Execution failed for task ':app:compileDebugGroovyWithGroovyc'.
> Compilation failed; see the compiler error output for details.
```

When I remove the ```@CompileStatic``` on my activity everything compiles and runs quite nicely.

**Comment by psh** [comment]
Looks like the databinding plugin generates its source in a strange location - ```build/intermediates/classes/<variant>``` - which may not be a location that the Groovy plugin is looking to compile?

**Comment by pieces029** [comment]
Try adding `as ActivityMainBinding` to that line.

`ActivityMainBinding binding = DataBindingUtil.setContentView(this, R.layout.activity_main) as ActivityMainBinding`

**Comment by MiguelAngelLV** [comment]
When I use Android Data Biding in groovy, I get error compiling XML. Any how to integrate groovy and data binding?

**Comment by pieces029** [comment]
Any updates on this issues?

Could you try this with the latest snapshot and see if the issue has been fixed?

**Comment by pieces029** [comment]
This works with compile static, but there is either need to use the apt plugin or to just accept that code completion doesn't work. 

Here is a sample project https://github.com/pieces029/groovy-android-data-binding

Leaving open so that I will remember to document this.

**Comment by pieces029** [comment]
The binding can be done either 

`def binding = DataBindingUtil.setContentView(this, R.layout.activity_main) as ActivityMainBinding`

or 

`def binding = DataBindingUtil.<ActivityMainBinding>setContentView(this, R.layout.activity_main)`

to allow compileStatic to work.

**Comment by turing-king** [comment]
@pieces029 
Hello, I have some special circumstances, does not generate data binding document

**Comment by pieces029** [comment]
@turing-king please open a sperate issue containing a test or an example of the issue you are having.

**Comment by r-gurzkowski** [comment]
Maybe this is related - after update to .10 I get:
Could not write to ***.BR javax.annotation.processing.FilerException: Attempt to recreate a file for type ***.BR

**Comment by pieces029** [comment]
@r-gurzkowski please create a separate issue containing a sample project or a failing test so that your issue may be investigated.

**Comment by pieces029** [comment]
Added in #115
