### ISSUE TITLE
Problem working with array in Android Studio

### ISSUE THREAD

**Issue by armandogc** [groovy/groovy-android-gradle-plugin#51]
I have a problem working with String-arrays in Android Studio (1.2.2) and Groovy pluggin (gradle-groovy-android-plugin:0.3.6)

The code works fine in my phone and emulators, but is a bit annoying when I wrote it. Here is the problem:

I define an array in strings.xml:

    <string-array name="days_list">
        <item>Monday</item>
        <item>Tuesday</item>
        <item>Wednesdey</item>
    </string-array>

After build project, the array is in "R" class:

    public static final class array {
        public static final int days_list=0x7f0c0001;
    }

But when I'm going to use this array in de Activity, the IDE didn't recognize it:

![array_1](https://cloud.githubusercontent.com/assets/6432123/8284817/6cb50cf0-18ff-11e5-8f81-40e3c9d089f8.png)

Also, days_list array is not in the content assits

![array_2](https://cloud.githubusercontent.com/assets/6432123/8284844/9e45ea3c-18ff-11e5-978b-cfb81a5ce44b.png)

As I said, this code works well in the App running on my device, but it is disturbing.

**Comment by pieces029** [comment]
That's just Android Studio being dumb, there really isn't anything this plugin can do about it (afaik). I have the same issue with R files and importing certain groovy libraries (specifically spock). Using IntelliJ has gotten rid of some of these issues.

**Comment by armandogc** [comment]
Ok, thanks for the explanation.
