### ISSUE TITLE
Feature request: androidGroovy option to always enable static compile

### ISSUE THREAD

**Issue by tobykurien** [groovy/groovy-android-gradle-plugin#52]
I would prefer to enable ```@CompileStatic``` by default on all Groovy classes in my Android project. To save me from manually adding that to the top of all classes, would it be possible to have an option I can enable in the ```build.gradle``` file to treat all Groovy code as statically compiled?

**Comment by safwankamarrudin** [comment]
+1 to this.

**Comment by melix** [comment]
You can already do this:

```
androidGroovy {
   options.groovyOptions.configurationScript = file("$projectDir/config/groovy-compile-options.groovy")
}
```

and then in your groovy-compile-options.groovy file:

```
withConfig(configuration) {
    ast(groovy.transform.CompileStatic)
}
```

**Comment by tobykurien** [comment]
Ok thanks. Would the Android Studio Groovy editor pick this up and mark static compile errors, or would it assume the code is dynamic?

**Comment by melix** [comment]
It will assume the code is dynamic.

2015-07-10 14:11 GMT+02:00 Toby Kurien <notifications@github.com>:

**Comment by tobykurien** [comment]
:-(
