### ISSUE TITLE
android build system 1.3 support missing?

### ISSUE THREAD

**Issue by dsvensson** [groovy/groovy-android-gradle-plugin#53]
I think I've updated my build.gradle files properly according to:

https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/gradle-experimental

However, the build doesn't work:

    * What went wrong:
    A problem occurred evaluating project ':app'.
    > Failed to apply plugin [id 'groovyx.grooid.groovy-android']
       > You must apply the Android plugin or the Android library plugin before using the groovy-android plugin

My app/build.gradle starts with:

    apply plugin: 'com.android.model.application'
    apply plugin: 'groovyx.grooid.groovy-android'

The fallback is to enable the deprecated NDK-support in the old version of the build system, but this will be the default environment in the near future.

**Comment by pieces029** [comment]
I'm not sure model in `apply plugin: 'com.android.model.application'` is correct, I it should be `apply plugin: 'com.android.application'`
