### ISSUE TITLE
[Question] Does it make sense to add emerger plugin functionality into Groovy plugin ?

### ISSUE THREAD

**Issue by mariogarcia** [groovy/groovy-android-gradle-plugin#54]
I've created the following plugin: https://github.com/kaleidos/emerger

Basically it merges Extension Module descriptors coming from different dependencies into one avoiding Android limitation of many files with same name in the same path.

I was wondering if it makes sense to add it to the Groovy plugin as it is something that all Groovy/Android projects may need.

**Comment by melix** [comment]
Nice. I would at least add a note to the documentation to explain that it exists. Having both separate still makes sense to me.

**Comment by pieces029** [comment]
Closing as this has been added to the documentation. Nice work @mariogarcia !
