### ISSUE TITLE
Unable to instantiate activity ComponentInfo

### ISSUE THREAD

**Issue by KingHanWen** [groovy/groovy-android-gradle-plugin#57]
java.lang.ClassNotFoundException: Didn't find class "com.lengking.myandroidcommon.test" on path: DexPathList[dexElements=[zip file "/data/app/com.lengking.myandroidcommon-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.lengking.myandroidcommon-2, /vendor/lib, /system/lib]]

      Programs compiled to run only the first time, after modification groovy file in the code can not be updated

**Comment by pieces029** [comment]
Do you have proguard turned on? Also could you post your Activity or other code which may be helpful for debugging.

**Comment by pieces029** [comment]
I haven't heard back for a while so I'm closing, feel free to reopen if you are still having issues
