### ISSUE TITLE
Unit test compilation not working because of wrong Java Unit Test compilation task name

### ISSUE THREAD

**Issue by wojtekerbetowski** [groovy/groovy-android-gradle-plugin#58]
It seems Google team has changed some tasks names (again).
Now it causes Groovy plugin to skip adding unit test compilation task.

It doesn't fail because of the `if` statement below:

```
// Unit tests (android plugin >= 1.1.0)
def unitTestTaskName = javaCompile.name.replaceFirst('Java', 'UnitTestJava')
def unitTestCompile = project.getTasksByName(unitTestTaskName,false)
if (unitTestCompile) {
  unitTestCompile.each { task ->
  groovyPlugin.attachGroovyCompileTask(project, plugin, task, ['test'])
}
```

**Comment by melix** [comment]
@pieces029 willing to take a look at this one?

**Comment by wojtekerbetowski** [comment]
This is working in master now (not yet in 0.3.6). A 3.7.0 release would be nice! :-)

Cheers
