### ISSUE TITLE
Very high method count

### ISSUE THREAD

**Issue by psh** [groovy/groovy-android-gradle-plugin#65]
I recently had to move a Groovy Android app over to *multi-dex* because it blew through the 64k method limit.  The build time (as you can imagine) ballooned due to *multi-dex*.

I created another application with a single activity, and a representative sample of 3rd party libraries (Google's material support lib, recyclerview, Joda time, Square Retrofit and of course Groovy).  I took a look at which libraries were contributing most to my overall count using the ```com.getkeepsafe.dexcount``` gradle plugin.  The available documentation on writing Groovy apps for Android says it consumes ~8k methods.  In my analysis, its *way* bigger than that.

My dependencies:
```groovy
dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile 'org.codehaus.groovy:groovy:2.4.3:grooid'
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.android.support:cardview-v7:22.2.1'
    compile 'com.android.support:recyclerview-v7:22.2.1'
    compile 'com.android.support:design:22.2.1'
    compile 'org.zeromq:jeromq:0.3.5'
    compile 'joda-time:joda-time:2.8.1'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.4.0'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.squareup.okio:okio:1.5.0'
    compile 'com.univocity:univocity-parsers:1.5.6'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.0@aar') {
        transitive = true;
    }
}
```

Gathering together all of the things associated with Groovy - approx 28,000 total
* 19584 methods - org.codehaus.groovy      
* 3237 methods - groovy                   
* 3072 methods - groovyjarjarantlr        
* 1319 methods - groovyjarjarasm          
* 815 methods - groovyjarjaropenbeans    
* 219 methods - groovyjarjarcommonscli   
* 174 methods - groovyjarjarharmonybeans 

For comparison
* 1766 methods - com.squareup.okhttp      
* 1199 methods - io.fabric                
* 964 methods - com.google.gson          
* 950 methods - com.crashlytics          
* 900 methods - com.univocity            
* 492 methods - retrofit                 
* 491 methods - okio                     

And, Android itself
* 17430 methods - android                  

Running ```gradlew app:dependencies``` told me:
```
+--- com.android.support:multidex:1.0.1
+--- org.codehaus.groovy:groovy:2.4.3
+--- com.android.support:appcompat-v7:22.2.1
|    \--- com.android.support:support-v4:22.2.1
|         \--- com.android.support:support-annotations:22.2.1
+--- com.android.support:cardview-v7:22.2.1
+--- com.android.support:recyclerview-v7:22.2.1
|    +--- com.android.support:support-annotations:22.2.1
|    \--- com.android.support:support-v4:22.2.1 (*)
+--- com.android.support:design:22.2.1
|    +--- com.android.support:appcompat-v7:22.2.1 (*)
|    \--- com.android.support:support-v4:22.2.1 (*)
+--- org.zeromq:jeromq:0.3.5
+--- joda-time:joda-time:2.8.1
+--- com.squareup.retrofit:retrofit:1.9.0
|    \--- com.google.code.gson:gson:2.3.1
+--- com.squareup.okhttp:okhttp-urlconnection:2.4.0
|    \--- com.squareup.okhttp:okhttp:2.4.0
|         \--- com.squareup.okio:okio:1.4.0 -> 1.5.0
+--- com.squareup.okhttp:okhttp:2.4.0 (*)
+--- com.squareup.okio:okio:1.5.0
+--- com.univocity:univocity-parsers:1.5.6
\--- com.crashlytics.sdk.android:crashlytics:2.5.0
     +--- io.fabric.sdk.android:fabric:1.3.5
     +--- com.crashlytics.sdk.android:crashlytics-core:2.3.3
     +--- com.crashlytics.sdk.android:answers:1.3.0
     |    \--- io.fabric.sdk.android:fabric:1.3.5
     \--- com.crashlytics.sdk.android:beta:1.1.3
```
Which all looks pretty sane to me.  Is this something other users are seeing?  Is there a slimmer and more *svelte* Groovy runtime that I can depend on?

Thanks!

**Comment by mradzinski** [comment]
+1, I've been noticing the same. Had to multi-dex my application and compilation now takes around 5 minutes :disappointed:

**Comment by psh** [comment]
Just for a sanity check, I used a recently announced website (www.methodscount.com) to check the count.

http://www.methodscount.com/?lib=org.codehaus.groovy%3Agroovy%3A2.4.3

They found a value of 28751 methods.

**Comment by blackdrag** [comment]
what about using ProGuard to reduce the jar size?

**Comment by sdelamo** [comment]
http://developer.android.com/intl/es/tools/help/proguard.html

    ProGuard runs only when you build your application in release mode, so you do not have to deal with     
    obfuscated code when you build your application in debug mode. 

As far as I understand proguard will help when you build your application for release but while developing you will need to turn multi-dex on when you hit the 64k method limit. And multi-dex really slows down compilation.

**Comment by pieces029** [comment]
You can run proguard in dev mode. 

```groovy
buildTypes {
      debug {
           minifyEnabled true
      }
}
``` 

This is what I have been doing to avoid blowing the dex count. You can get fancy and disable proguard if you are running on a device that is > 21 which will speed up your build a bit.

**Comment by sdelamo** [comment]
thanks a lot @pieces029 !

**Comment by pieces029** [comment]
Since this isn't an issue with the plugin, can this issue be closed out? 

I believe questions like this are more suited for places like stackoverflow, where github issues be left open for issues regarding this plugin.
