### ISSUE TITLE
Documentation, perhaps: How to use Groovy Utils?

### ISSUE THREAD

**Issue by EdwardIII** [groovy/groovy-android-gradle-plugin#66]
I've checked out the very helpful example here (maybe linking to this project from the README might be cool?):

https://github.com/melix/gr8confagenda/blob/master/gr8confagenda/build.gradle

But when I try and use it in my project I get:

    20: unable to resolve class XmlSlurper

It's probably just that I'm being really green. I tried to see if I could compile just groovy.util to get access to the [XmlSlurper](http://docs.groovy-lang.org/latest/html/api/groovy/util/XmlSlurper.html)  but I couldn't see it as being split-out on Maven, I guess it's in with groovy core?

If I add groovy-all to my compile deps then I see:

    com.android.dex.DexException: Multiple dex files define Lgroovy/beans/Bindable;

What's the right approach here?

**Comment by melix** [comment]
You cannot use `groovy-all` because it's the "desktop" version of the Groovy runtime. You need to add a dependency on `groovy-xml`.

**Comment by EdwardIII** [comment]
But I think XmlSlurper is in groovy.util rather than groovy.xml?

**Comment by melix** [comment]
You are mixing the package name with the artifact name. `XmlSlurper` is found in the `groovy.util` package in the `groovy-xml` module.

**Comment by EdwardIII** [comment]
@melix Thanks for your patience - when I try to build after adding the groovy-xml dep I start seeing lint errors like this:

    Invalid package reference in library; not included in Android: java.applet. Referenced from groovyjarjaropenbeans.Beans.

Here's the full build file:

https://github.com/EdwardIII/rugby-bins/blob/master/build.gradle

**Comment by pieces029** [comment]
@EdwardIII where are you seeing these lint errors? Is you project able to compile?

**Comment by pieces029** [comment]
@EdwardIII do you have any update on this, what kind of documentation are you looking for?

I was thinking something along the lines of libraries that include groovy as a dependency should be excluded since android applications require the grooid classifier.

ex
```groovy
compile ('org.codehaus.groovy:groovy-xml:2.4.3') {
    exclude group: 'org.codehaus.groovy'
}
```

**Comment by EdwardIII** [comment]
Hey let me check it out

**Comment by pieces029** [comment]
Added in #115
