### ISSUE TITLE
Performance problem, not sure if this is to be expected or not.

### ISSUE THREAD

**Issue by dealy663** [groovy/groovy-android-gradle-plugin#67]
Hi

I've just started using the groovy android gradle plugin. My APK is extracting a Jar archive , but is going very slowly proceeding at only about 3k bytes/second. It does this by iterating through the elements of a JarFile object and creating a FileOutputstream for each file it pulls from the archive. This all works at a normal pace when I run this Groovy class in my computer.

I specified @CompileStatic on my Groovy class.

Is there something about the way that I'm doing this that would cause Groovy to so slow? Are there some other changes I need to make in my build to get this to work at a better pace?

Thanks, Derek

**Comment by pieces029** [comment]
What do you mean by

> My APK is extracting a Jar archive

**Comment by Paradoxia** [comment]
@dealy663 Might be a problem with the buffer size. Try something like this.
```
def file = new File('/path/to/file')

// Create an output stream that writes to the file in 'append' mode
def fileOutput = new FileOutputStream(file, true)

// Buffer the output - set bufferSize to whatever size buffer you want to use
def bufferSize = 512
def fileOutput = new BufferedOutputStream(fileOutput, bufferSize)

try {
    byte[] contentToAppend = // Get the content to write to the file
    fileOutput.write(contentToAppend)
} finally {
    fileOutput.close()
}
```

**Comment by pieces029** [comment]
@dealy663 are there any updates to this? 

This looks like an issue with code, and not specifically the groovy-android-plugin.

**Comment by pieces029** [comment]
Closing this issue as there has not been any update. Please feel free to re-open if you feel that this was prematurely closed.
