### ISSUE TITLE
SNAPSHOT artifact is not deployed to jcenter

### ISSUE THREAD

**Issue by dbacinski** [groovy/groovy-android-gradle-plugin#68]
SNAPSHOT artifact is not deployed to jcenter, 0.3.7-SNAPSHOT is missing:
https://oss.jfrog.org/artifactory/oss-snapshot-local/org/codehaus/groovy/gradle-groovy-android-plugin/

During build there is an error:
Caused by: org.gradle.internal.UncheckedException: java.io.IOException: Failed to deploy file: HTTP response code: 401. HTTP response message: Unauthorized

https://travis-ci.org/groovy/groovy-android-gradle-plugin/builds/82164779

**Comment by dbacinski** [comment]
Until fix jitpack artifact can be used:
https://jitpack.io/#groovy/groovy-android-gradle-plugin/1b77dd6763

**Comment by pieces029** [comment]
@dbacinski Thanks! 

@melix Is there anything I can do to help get this project building and deploying again?

**Comment by jaredsburrows** [comment]
+1

**Comment by jaredsburrows** [comment]
@pieces029 Now that you are an owner, can you help maintain this? :)

**Comment by pieces029** [comment]
@jaredsburrows yup!

**Comment by pieces029** [comment]
Trying to resolve the travis ci issue. For some reason there is an overflow during the build and nothing in that area seems to have changed. If anyone can provide other insights that would be great. Otherwise, I'm exploring other CI options.

**Comment by pieces029** [comment]
0.3.7-SNAPSHOT is now available from jcenter. This is not yet automated, so I will leave this issue open until travis is fixed / move to different ci.

**Comment by pieces029** [comment]
travis has been fixed.

**Comment by jaredsburrows** [comment]
Very good job! I am glad you are an owner on this now. This project has
needed maintenance.
