### ISSUE TITLE
when debug groovy, raise "org.codehaus.groovy.control.MultipleCompilationErrorsException"

### ISSUE THREAD

**Issue by roroco** [groovy/groovy-android-gradle-plugin#70]
[here](http://stackoverflow.com/questions/34272312/when-use-groovy-raise-org-codehaus-groovy-control-multiplecompilationerrorsexc) is my stackoverflow question, which version can debug groovy?

**Comment by pieces029** [comment]
Are you using compile static? How is your build setup?

**Comment by roroco** [comment]
I fork gr8confagenda to [here](https://github.com/roroco/gr8confagenda) and get [screenshot](https://www.dropbox.com/s/as1j81878far3mb/adr-cannot-dbg-gvy.png?dl=0), 
"bar" in "variables tool window" work well, but "bar" in "watches" doesn't work

**Comment by pieces029** [comment]
This is looks to be an issue with Android Studio. Have you tried using IntelliJ, and or submitting a bug to Android Studio? https://code.google.com/p/android/issues/list

**Comment by pieces029** [comment]
Please refer to this issue as well https://github.com/groovy/groovy-android-gradle-plugin/issues/47

Closing this issue, but if you feel like this is a problem with the plugin feel free to re-open.
