### ISSUE TITLE
Create Sample Project

### ISSUE THREAD

**Issue by pieces029** [groovy/groovy-android-gradle-plugin#75]
A sample project that shows off how to use lots of different aspects of groovy and demonstrates why groovy is a good choice to use on Android and how to properly use it to help explain and coincide with the documentation would be very beneficial.

**Comment by sdelamo** [comment]
Don't know if this is useful for what you are looking for but I worked on https://github.com/sdelamo/botconf for recent talk. 

It illustrates several groovy goodies in an android app. The android app features a quite standard architecture. A SQLite persistence layer, a remote sever, etc.
 
The work is far from done but I want to continue working on it after christmas is over.

**Comment by pieces029** [comment]
@sdelamo Possibly, the sample project I would want added as a module to this project.
