### ISSUE TITLE
Plugin only supports the application variant

### ISSUE THREAD

**Issue by jparks** [groovy/groovy-android-gradle-plugin#9]
The plugin only allows Groovy files to appear in the application variant. This does not allow for Groovy to appear in libraries or tests. Support for the library and test variants would be awesome!

**Comment by IgorGanapolsky** [comment]
I am still getting this error with `org.codehaus.groovy:gradle-groovy-android-plugin:0.3.6`.  Is there a solution?

**Comment by pieces029** [comment]
@IgorGanapolsky Yes, use 1.0.0

**Comment by IgorGanapolsky** [comment]
@pieces029 Not possible, I get an error:
> Error:(25, 1) A problem occurred evaluating root project 'CrestronApp_Android'.
Failed to apply plugin [id 'groovyx.android']
You must apply the Android plugin or the Android library plugin before using the groovy-android plugin
