### ISSUE TITLE
Can not see variable's value in Android Studio debugger

### ISSUE THREAD

**Issue by cvoronin** [groovy/groovy-android-gradle-plugin#90]
Android studio 1.5.1
org.codehaus.groovy:groovy:2.4.5:grooid
classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.8'

When in debbuger I alt-click on the variable, I get such an error-message:
![ashampoo_snap_2016 02 11_14h18m31s_002_](https://cloud.githubusercontent.com/assets/2241595/12974612/27c29bd6-d0d7-11e5-8356-73f27ebdb4cc.png)

When I place cursor over a variable, I see:
![ashampoo_snap_2016 02 11_14h24m25s_005_](https://cloud.githubusercontent.com/assets/2241595/12974609/16c22856-d0d7-11e5-9154-bc87c8cc3b49.png)

This issue seems to be related with https://github.com/groovy/groovy-android-gradle-plugin/issues/47
However in this case I see no way to switch between Groovy/Java

**Comment by pieces029** [comment]
This is not an issue with the android-groovy plugin. Rather an issue with Android Studio. 
Some workaround ideas are to use IntelliJ, or try using the watches window.

I would suggest filing a bug with Android Studio if you want to see this issue fixed. https://sites.google.com/a/android.com/tools/filing-bugs

**Comment by MaximoB** [comment]
I am still getting this error even using the watches window.
Android Studio 3.0.1 and Groovy plugin version 2.4.11.
Maybe you could explain how it's and Android Studio bug if it only effects Groovy projects? A bug report to Google results in them saying they don't support Groovy so what am I supposed to do here?
Even if this is an Android Studio bug it makes this project crippled and unusable so it should be a priority to fix it. As it stands I am now migrating my project off Groovy ASAP.
