### ISSUE TITLE
Location of project.androidGroovy

### ISSUE THREAD

**Issue by cvoronin** [groovy/groovy-android-gradle-plugin#91]
Could you, please, specify the correct location of
project.androidGroovy {...}

Should it be inserted as top-level item in .gradle or, for example, inside the android {...} block?

groovy-android-sample-app seems to be a good place for this example.

![ashampoo_snap_2016 02 11_16h40m02s_006_](https://cloud.githubusercontent.com/assets/2241595/12975512/300d8f9c-d0de-11e5-898e-f8b5f9918948.png)

**Comment by pieces029** [comment]
Top level like you have your screenshot.

I'll add an example when I get the chance, otherwise adding this to the example would be a very helpful contribution.
