### ISSUE TITLE
incompatibility with com.neenbedankt.android-apt 1.8

### ISSUE THREAD

**Issue by laenger** [groovy/groovy-android-gradle-plugin#96]
There seems to be an issue when using the `com.neenbedankt.android-apt` plugin version 1.8 together with this groovy plugin (0.3.8) and spock unit tests. the build fails when one of the apt src dirs does not exist (because there are no generated test sources). it seems the build should probably skip these folders. apt-plugin version 1.4 works fine since it does not support generated classes for tests.

error:
```
* What went wrong:
Execution failed for task ':app:compileDevDebugUnitTestGroovyWithGroovyc'.
> directory not found: .../app/build/generated/source/apt/test/dev/debug
```
buildscript:
```
dependencies {
    classpath 'com.android.tools.build:gradle:1.5.0'
    classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.8'
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
}
```
app:
```
dependencies {
    ....
    testCompile 'org.codehaus.groovy:groovy:2.4.5:grooid'
    testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'
    ....
}
```

**Comment by pjakubczyk** [comment]
I'm facing similar problem when update to 1.8. It's not possible to compile class with custom Spock Runner.

btw @laenger did you try https://github.com/robospock/RoboSpock :) ?

**Comment by pieces029** [comment]
Could you try out the `0.3.9-SNAPSHOT`? I've pretty much rewritten how the source directories are added to the groovy compile task.

**Comment by laenger** [comment]
@pieces029 that snapshot works indeed! thank you for the hint :)
@pjakubczyk i haven't in a while since i currently only need plain unit tests

**Comment by pieces029** [comment]
@laenger great! I plan to have a release cut soon.

**Comment by pieces029** [comment]
0.3.9 released!
